#![allow(unused_imports, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod addressupgradeable;
pub mod checkpointsupgradeable;
pub mod contextupgradeable;
pub mod counter;
pub mod ecdsaservicemanagerbase;
pub mod ecdsastakeregistry;
pub mod ecdsastakeregistryeventsanderrors;
pub mod ecdsastakeregistrystorage;
pub mod ecdsaupgradeable;
pub mod iavsdirectory;
pub mod idelegationmanager;
pub mod ierc1271upgradeable;
pub mod ierc165;
pub mod ierc20;
pub mod ierc721;
pub mod ierc721enumerable;
pub mod ierc721metadata;
pub mod ierc721tokenreceiver;
pub mod ilayerservicemanager;
pub mod ilayertrigger;
pub mod initializable;
pub mod iregistry;
pub mod irewardscoordinator;
pub mod iservicemanager;
pub mod iservicemanagerui;
pub mod isignatureutils;
pub mod istakeregistry;
pub mod istrategy;
pub mod mathupgradeable;
pub mod mockerc20;
pub mod mockerc721;
pub mod ownableupgradeable;
pub mod safecastupgradeable;
pub mod signaturecheckerupgradeable;
pub mod stringsupgradeable;
pub mod wavsservicemanager;
pub mod wavstrigger;
